### ISSUE TITLE
`buildSnapshotResolver` throws when not using the default root directory

### ISSUE THREAD

**Issue by heyitsaamir** [mochiya98/mocha-chai-jest-snapshot#5]
This part of the code tries to build a snapshot with "default" on the import. If the resolver lives somewhere else than default, then buildSnapshotResolver will throw. Can we not build a resolver on import?

https://github.com/mochiya98/mocha-chai-jest-snapshot/blob/352285bbee10fc13d105376bcfcff90fa5b114cb/src/helper.ts#L8-L11

**Comment by mochiya98** [comment]
That code was left unused and doesn't affect the actual behavior.
I removed the code to avoid confusion.
Thanks.
